name: remote ssh command
on: [push]
jobs:

  update:
    name: update
    runs-on: ubuntu-latest
    steps:
    - name: upload to server and build
      uses: appleboy/ssh-action@master
      with:
        password: ${{ secrets.PASSWORD }}
        script: cd /root/repetitor && git pull && docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml up -d
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
